version: "3.9"

services:
  build-agent:
    build: build-agent
    ports:
      - 4646:4646
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    stop_signal: SIGKILL
    stop_grace_period: 1s
